CREATE TABLE marmSchedulerTasks 
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 active TINYINT(1) NOT NULL,
 path VARCHAR(255) NOT NULL,
 class VARCHAR(255) NOT NULL,
 description VARCHAR(255) NOT NULL,
 starttime INT NOT NULL,
 timeinterval INT NOT NULL,
 lastrun INT NOT NULL);

CREATE TABLE marmSchedulerLog
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 taskid INT NOT NULL,
 class VARCHAR(255) NOT NULL,
 success TINYINT(1) NOT NULL,
 message VARCHAR(255) NOT NULL,
 time INT NOT NULL,
 runtime INT NOT NULL);
